[package]
name = "AI_Snake_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.16.1", features = ["serde"] }
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
